update: change some coding styles

diff --git a/commands/setter b/commands/setter
--- a/commands/setter
+++ b/commands/setter
@@ -1,27 +1,28 @@
 #!/usr/bin/env bash
 
-# this script is used for judging a solution and generating output locally
+# this script is used for judging a solution
+# and generating output locally
 #
 
-VERSION="0.0.1"
-SCRIPT_NAME="$(basename "$0")"
+declare -r __script_name='setter'
+declare -r __script_version='0.1.2'
 
 function usage() {
   cat << EOF
-Usage: $SCRIPT_NAME [options...] <command>
+Usage: ${__script_name} [options...] <command>
 
 Options:
-  -h, --help            Show this help
-  -V, --version         Show version number
+  -h, --help            Show this help message
+  -V, --version         Show script version
 
 Available commands:
-  judge                 Run and check the solution
+  judge                 Judge your solution
   gen                   Generate output from input files
 EOF
 }
 
-function display_version() {
-  echo "$SCRIPT_NAME version ${VERSION}"
+function version() {
+  printf "%s v%s\n" "${__script_name}" "${__script_version}"
 }
 
 exec_file="$(readlink -f "$0")"
@@ -34,14 +35,16 @@ case "$subcommand" in
   "" | -h | --help)
     usage; exit 0 ;;
   -V | --version)
-    display_version; exit 0 ;;
+    version; exit 0 ;;
   -*)
-    echo "Unknown option: $subcommand" >&2
-    usage; exit 2 ;;
+    printf "%s: invalid option '%s'\n" "${__script_name}" "$subcommand" >&2
+    printf "See '%s --help' for more information.\n" "${__script_name}" >&2
+    exit 2 ;;
   *)
-    command_path="$(command -v "${SCRIPT_NAME}-${subcommand}")"
+    command_path="$(command -v "${__script_name}-${subcommand}")"
     if [[ ! -x "$command_path" ]]; then
-      echo "${SCRIPT_NAME}: unknown command '$1'. See ${SCRIPT_NAME} --help." >&2
+      printf "%s: unknown command '%s'\n" "${__script_name}" "$subcommand" >&2
+      printf "See '%s --help' for more information.\n" "${__script_name}" >&2
       exit 127
     fi
     shift
diff --git a/commands/setter-gen b/commands/setter-gen
--- a/commands/setter-gen
+++ b/commands/setter-gen
@@ -3,52 +3,52 @@
 # generating output files from provided input files
 #
 # requires:
-#   time (not a built-in keyword one)
+#   time (not a shell keyword one)
 #
+
+declare -r __script_name='setter gen'
 
 if [ -f "${_SETTER_ROOT_DIR}/env/colors.sh" ]; then
   . "${_SETTER_ROOT_DIR}/env/colors.sh" 
 fi
 
-SCRIPT_NAME="$(basename "$0" | tr '-' ' ')"
-
-function usage() {
-  cat << EOF
-Usage: $SCRIPT_NAME [options...]
-
-Options:
-  -h, --help                Show this help
-  -c, --checker <file>      Checker file to run (default: checker.out)
-  -i, --input-dir <dir>     Directory that contains input files (default: in)
-  -o, --output-dir <dir>    Directory to place output files (default: out)
-EOF
-}
-
-options='hc:i:o:'
-long_options='help,checker:,input:,output:'
-
-OPTS=$(getopt --name "$SCRIPT_NAME" --options "$options" \
-      --longoptions "$long_options" -- "$@")
-
-if (( $? != 0 )); then
-  usage
-  exit 2
-fi
-eval set -- "$OPTS"
-
-input_dir="./in"
-output_dir="./out"
-checker="./checker.out"
-time_command="$(which time)" # do not use a bash built-in keyword
+input_dir="in"
+output_dir="out"
+checker="checker.out"
+time_command="$(which time 2> /dev/null)" # do not use shell keyword
 if [[ -z "$time_command" ]]; then
-  echo "${SCRIPT_NAME}: 'time' command is required but not found"
+  printf "%s: 'time' command is required but not found\n" "${__script_name}" >&2
   exit 127
 fi
 
 if ! which timeout &> /dev/null; then
-  echo "${SCRIPT_NAME}: 'timeout' command is required but not found"
+  printf "%s: 'timeout' command is required but not found\n" "${__script_name}" >&2
   exit 127
 fi
+
+function usage() {
+  cat << EOF
+Usage: ${__script_name} [options...]
+
+Options:
+  -c, --checker <file>      Checker file to run (default: ${checker})
+  -i, --input-dir <dir>     Directory that contains input files (default: ${input_dir})
+  -o, --output-dir <dir>    Directory to place output files (default: ${output_dir})
+  -h, --help                Show this help message
+EOF
+}
+
+options='c:i:o:h'
+long_options='checker:,input:,output:,help'
+
+OPTS=$(getopt --name "$__script_name" --options "$options" \
+      --longoptions "$long_options" -- "$@")
+
+if (( $? != 0 )); then
+  printf "See '%s --help' for more information.\n" "${__script_name}" >&2
+  exit 2
+fi
+eval set -- "$OPTS"
 
 while true; do
   case "$1" in
@@ -67,36 +67,38 @@ while true; do
   esac
 done
 
-if [[ "$(basename "$checker")" == "$checker" ]]; then
-  checker="./${checker}"
-fi
-
-if [[ ! -x "$checker" ]]; then
-  echo "Could not find checker file or not a executable file '${checker}'"
+if [[ ! -f "$checker" ]]; then
+  printf "Could not find checker file '%s'\n" "${checker}" >&2
   exit 2
 fi
 
 if [[ ! -d "$input_dir" ]]; then
-  echo "Could not find input directory '${input_dir}'"
+  printf "Could not find input directory '%s'\n" "${input_dir}" >&2
   exit 2
 fi
 
 if [[ -d "$output_dir" ]]; then
-  echo -n "Directory $output_dir already exists. Overwrite? [Y/n] "
+  printf "Directory '%s' already exists. Overwrite? [Y/n] " "$output_dir"
   read answer
   case "$answer" in 
     y | Y)
       rm -rf "$output_dir" ;;
     *)
-      echo "Aborted"; exit 0 ;;
+      printf "Aborted\n" >&2; exit 1 ;;
   esac
 fi
+
 mkdir -p "$output_dir"
 
-input_num=$(ls "${input_dir}"/*.in 2> /dev/null | wc -l)
+if [[ "$(basename "$checker")" == "$checker" ]]; then
+  checker="./${checker}"
+fi
+
+input_num=$(find "$input_dir" -iname "*.in" | wc -l)
 
 if (( input_num == 0 )); then
-  echo "No input file (*.in) found in $input_dir"
+  printf "No input file found in '%s'\n" "$input_dir" >&2
+  printf "Aborted\n" >&2
   exit 2
 fi
 
diff --git a/commands/setter-judge b/commands/setter-judge
--- a/commands/setter-judge
+++ b/commands/setter-judge
@@ -7,25 +7,39 @@
 #   timeout
 #
 
+declare -r __script_name='setter judge'
+
 if [ -f "${_SETTER_ROOT_DIR}/env/colors.sh" ]; then
   . "${_SETTER_ROOT_DIR}/env/colors.sh" 
 fi
 
-SCRIPT_NAME="$(basename "$0" | tr '-' ' ')"
+src_file="sol.out"
+input_dir="in"
+output_dir="out"
+time_limit="1s"
+memory_limit="256MB"
+time_command="$(which time)"
+if [[ -z "$time_command" ]]; then
+  printf "%s: 'time' command is required but not found\n" "${__script_name}" >&2
+  exit 127
+fi
+if ! which timeout &> /dev/null; then
+  printf "%s: 'timeout' command is required but not found\n" "${__script_name}" >&2
+  exit 127
+fi
 
 function usage() {
   cat << EOF
-Usage: $SCRIPT_NAME [options...]
+Usage: ${__script_name} [options...]
 
 Options:
-  -h, --help                Show this help
-  -s, --source <file>       Source file to check (default: solution.out)
-  -i, --input-dir <dir>     Directory that contains input files (default: in)
-  -o, --output-dir <dir>    Directory to place output files (default: out)
-  -t, --time <second>       Set time limit (default: 1s)
-  -m, --memory <memory>     Set memory limit (default: 256MB)
+  -s, --source <file>       Source file to check (default: ${src_file})
+  -i, --input-dir <dir>     Directory that contains input files (default: ${input_dir})
+  -o, --output-dir <dir>    Directory that contains output files (default: ${output_dir})
+  -t, --time <second>       Set time limit (default: ${time_limit})
+  -m, --memory <memory>     Set memory limit (default: ${memory_limit})
+  -h, --help                Show this help message
 EOF
-  exit 0
 }
 
 options='hs:i:o:t:m:'
@@ -40,27 +54,12 @@ if (( $? != 0 )); then
 fi
 eval set -- "$OPTS"
 
-input_dir="./in"
-output_dir="./out"
-source_file="./source.out"
-time_limit="1s"
-memory_limit="256MB"
-time_command="$(which time)"
-if [[ -z "$time_command" ]]; then
-  echo "${SCRIPT_NAME}: 'time' command is required but not found"
-  exit 127
-fi
-if ! which timeout &> /dev/null; then
-  echo "${SCRIPT_NAME}: 'timeout' command is required but not found"
-  exit 127
-fi
-
 while true; do
   case "$1" in
     -h | --help)
-      usage ;;
+      usage; exit 0;;
     -s | --source)
-      source_file="$2"; shift 2 ;;
+      src_file="$2"; shift 2 ;;
     -i | --input-dir)
       input_dir="$2"; shift 2 ;;
     -o | --output-dir)
@@ -76,25 +75,26 @@ while true; do
   esac
 done
 
-if [[ "$(basename "$source_file")" == "$source_file" ]]; then
-  source_file="./${source_file}"
-fi
-
-if [[ ! -x "$source_file" ]]; then
-  echo "Could not find source file or not a executable file '${source_file}'"
+if [[ ! -x "$src_file" ]]; then
+  printf "%s: could not find source file or not a executable file: %s\n" "${__script_name}" "${src_file}" >&2
   exit 2
 elif [[ ! -d "$input_dir" ]]; then
-  echo "Could not find input directory '${input_dir}'"
+  printf "Could not find input directory '%s'\n" "$input_dir" >&2
   exit 2
 elif [[ ! -d "$output_dir" ]]; then
-  echo "Could not find output directory '${output_dir}'"
+  printf "Could not find output directory '%s'\n" "$output_dir" >&2
   exit 2
 fi
 
-input_num=$(ls "${input_dir}"/*.in 2> /dev/null | wc -l)
+if [[ "$(basename "$src_file")" == "$src_file" ]]; then
+  src_file="./${src_file}"
+fi
+
+input_num=$(find "$input_dir" -iname "*.in" | wc -l)
 
 if (( input_num == 0 )); then
-  echo "No input file (*.in) found in $input_dir"
+  printf "No input file found in '%s'\n" "$input_dir" >&2
+  printf "Aborted\n" >&2
   exit 2
 fi
 
@@ -123,14 +123,14 @@ for input in "${input_dir}"/*.in; do
   fi
 
   timeout "$time_limit" "$time_command" -f "$exec_info_format" -o "$exec_info_file" \
-      "$source_file" < "$input" > "$output_temp_file"
+      "$src_file" < "$input" > "$output_temp_file"
   exec_exit_code=$?
   if (( exec_exit_code != 0 )); then
     if (( exec_exit_code == 124 )); then 
       # command times out 
       echo -e "\t${B_RED}TLE${RESET} (> $time_limit)"
     else
-      # assume exit code is returned by `source_file`
+      # assume exit code is returned by `src_file`
       echo -e "\t${B_RED}RUN TIME${RESET} (exit_code=$exec_exit_code)"
     fi
     exit_code=1
